repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.18.0
    hooks:
      - id: django-upgrade
        args: [ --target-version, "5.0" ]

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest stable release
    hooks:
      - id: black
        args: [ --line-length=110 ]
        language_version: python3.12  # Use the appropriate Python version
